apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "this.name" . }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "this.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "this.selectorLabels" . | nindent 8 }}
        {{- with .Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "this.name" . }}
      containers:
        - name: http-echo
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          args:
            {{- range .Values.args }}
            - {{ . }}
            {{- end }}
          ports:
            - name: {{ .Values.port.name }}
              containerPort: {{ .Values.port.number }}
          securityContext:
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
