apiVersion: v1
kind: Service
metadata:
  name: {{ include "this.name" . }}
  labels:
    {{- include "this.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "this.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.port.name }}
      targetPort: {{ .Values.port.number }}
      port: {{ .Values.port.number }}
