name: Release All

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Package Helm Chart
        run: |
          mkdir -p packaged
          helm package charts/* --destination packaged

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packaged/*

      - name: Update index.yaml in gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          helm repo index ./packaged --url https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }} --merge index.yaml
          mv ./packaged/index.yaml index.yaml
          git add index.yaml
          git commit -m "Update Helm repo index for ${{ github.ref_name }}"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
